security:
    encoders:
        Objects\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_USER:        ROLE_NOTACTIVE
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Objects\UserBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: login
                always_use_default_target_path: true
                use_forward: true
                default_target_path: redirect_user

            logout:
                path:   logout
                target: /

            remember_me:
                key:      "%secret%"
                # the next lifetime is in seconds (7days) max 86391359
                lifetime: 604800
                path:     /

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/user/auth, roles: ROLE_NOTACTIVE }
         - { path: ^/user/auth/active, roles: ROLE_USER }
         - { path: ^/user/auth/fully, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
