# Login routes
login_check:
    path:  /login-check

logout:
    path:  /logout

login:
    path:  /login/{isMain}
    defaults: { _controller: ObjectsUserBundle:User:login, isMain: false }

# routing files
user:
    resource: "@ObjectsUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
