services:
    page_admin:
      class: Objects\AdminBundle\Admin\PageAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Page }
      arguments: [null, Objects\AdminBundle\Entity\Page, SonataAdminBundle:CRUD]
    block_admin:
      class: Objects\AdminBundle\Admin\BlockAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Block }
      arguments: [null, Objects\AdminBundle\Entity\Block, SonataAdminBundle:CRUD]
    banner_admin:
      class: Objects\AdminBundle\Admin\BannerAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Banner }
      arguments: [null, Objects\AdminBundle\Entity\Banner, ObjectsAdminBundle:Banner]
    user_admin:
        class: Objects\AdminBundle\Admin\UserAdmin
        arguments: [~, Objects\UserBundle\Entity\User, ObjectsAdminBundle:User]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    objects_admin.admin.client:
        class: Objects\AdminBundle\Admin\ClientAdmin
        arguments: [~, Objects\KarasBundle\Entity\Client, ObjectsAdminBundle:Client]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    objects_admin.admin.slide:
        class: Objects\AdminBundle\Admin\SlideAdmin
        arguments: [~, Objects\KarasBundle\Entity\Slide, ObjectsAdminBundle:Slide]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Slide}

    objects_admin.admin.service:
        class: Objects\AdminBundle\Admin\ServiceAdmin
        arguments: [~, Objects\KarasBundle\Entity\Service, ObjectsAdminBundle:Service]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Service}

    objects_admin.admin.branch:
        class: Objects\AdminBundle\Admin\BranchAdmin
        arguments: [~, Objects\KarasBundle\Entity\Branch, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Branch}

    objects_admin.admin.about:
        class: Objects\AdminBundle\Admin\AboutAdmin
        arguments: [~, Objects\KarasBundle\Entity\About, ObjectsAdminBundle:About]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: About}

    objects_admin.admin.industry:
        class: Objects\AdminBundle\Admin\IndustryAdmin
        arguments: [~, Objects\KarasBundle\Entity\Industry, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Industry}

    objects_admin.admin.profession:
        class: Objects\AdminBundle\Admin\ProfessionAdmin
        arguments: [~, Objects\KarasBundle\Entity\Profession, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Profession}

    objects_admin.admin.experience:
        class: Objects\AdminBundle\Admin\ExperienceAdmin
        arguments: [~, Objects\KarasBundle\Entity\Experience, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Experience}

    objects_admin.admin.project:
        class: Objects\AdminBundle\Admin\ProjectAdmin
        arguments: [~, Objects\KarasBundle\Entity\Project, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Project}

    objects_admin.admin.course:
        class: Objects\AdminBundle\Admin\CourseAdmin
        arguments: [~, Objects\KarasBundle\Entity\Course, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Course}

    objects_admin.admin.skill:
        class: Objects\AdminBundle\Admin\SkillAdmin
        arguments: [~, Objects\KarasBundle\Entity\Skill, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Skill}

    objects_admin.admin.education:
        class: Objects\AdminBundle\Admin\EducationAdmin
        arguments: [~, Objects\KarasBundle\Entity\Education, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Education}

    objects_admin.admin.language:
        class: Objects\AdminBundle\Admin\LanguageAdmin
        arguments: [~, Objects\KarasBundle\Entity\Language, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Language}

    objects_admin.admin.job:
        class: Objects\AdminBundle\Admin\JobAdmin
        arguments: [~, Objects\KarasBundle\Entity\Job, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Job}
