services:
    page_admin:
      class: Objects\AdminBundle\Admin\PageAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Page }
      arguments: [null, Objects\AdminBundle\Entity\Page, SonataAdminBundle:CRUD]
    block_admin:
      class: Objects\AdminBundle\Admin\BlockAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Block }
      arguments: [null, Objects\AdminBundle\Entity\Block, SonataAdminBundle:CRUD]
    banner_admin:
      class: Objects\AdminBundle\Admin\BannerAdmin
      tags:
         - { name: sonata.admin, manager_type: orm, label: Banner }
      arguments: [null, Objects\AdminBundle\Entity\Banner, ObjectsAdminBundle:Banner]
#    user_admin:
#        class: Objects\AdminBundle\Admin\UserAdmin
#        arguments: [~, Objects\UserBundle\Entity\User, ObjectsAdminBundle:User]
#        tags:
#            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    objects_admin.admin.client:
        class: Objects\AdminBundle\Admin\ClientAdmin
        arguments: [~, Objects\KarasBundle\Entity\Client, ObjectsAdminBundle:Client]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Client}

    objects_admin.admin.slide:
        class: Objects\AdminBundle\Admin\SlideAdmin
        arguments: [~, Objects\KarasBundle\Entity\Slide, ObjectsAdminBundle:Slide]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Slide}

    objects_admin.admin.service:
        class: Objects\AdminBundle\Admin\ServiceAdmin
        arguments: [~, Objects\KarasBundle\Entity\Service, ObjectsAdminBundle:Service]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Service}

    objects_admin.admin.branch:
        class: Objects\AdminBundle\Admin\BranchAdmin
        arguments: [~, Objects\KarasBundle\Entity\Branch, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Branch}
