# routes that requires a login from the login page
user_delete:
    path: /auth/fully/delete
    defaults: { _controller: ObjectsUserBundle:User:deleteAccount }

# routes that requires logged in user
redirect_user:
    path: /auth/redirect-user
    defaults: { _controller: ObjectsUserBundle:User:redirectUser }

user_edit:
    path: /auth/edit
    defaults: { _controller: ObjectsUserBundle:User:edit }

twitter_link:
    path: /auth/twitter-link
    defaults: { _controller: ObjectsUserBundle:User:twitterLink }

facebook_link:
    path: /auth/facebook-link
    defaults: { _controller: ObjectsUserBundle:User:facebookLink }

linkedin_link:
    path: /auth/linkedin-link
    defaults: { _controller: ObjectsUserBundle:User:linkedinLink }

social_unlink:
    path: /auth/unlink/{social}
    defaults: { _controller: ObjectsUserBundle:User:socialUnlink }

user_reActivation:
    path: /user-reActivation
    defaults: { _controller: ObjectsUserBundle:User:reActivation }

# routes visible for every one
signup:
    path: /signup
    defaults: { _controller: ObjectsUserBundle:User:signUp }

user_active:
    path: /activation/{confirmationCode}/{email}
    defaults: { _controller: ObjectsUserBundle:User:activation }

google_enter:
    path: /google-enter
    defaults: { _controller: ObjectsUserBundle:User:GoogleEnter }

twitter_enter:
    path: /twitter-enter
    defaults: { _controller: ObjectsUserBundle:User:TwitterEnter }

facebook_logging:
    path: /facebook-logging
    defaults: { _controller: ObjectsUserBundle:User:facebook }

forgot_password:
    path: /forgot-password
    defaults: { _controller: ObjectsUserBundle:User:forgotPassword }

change_password:
    path: /change-password/{confirmationCode}/{email}
    defaults: { _controller: ObjectsUserBundle:User:changePassword }

linkedIn_user_data:
    path:  /linkedin
    defaults: { _controller: ObjectsUserBundle:User:linkedInUserData }

login_name_check:
    path: /login-name-check/{loginName}
    defaults: { _controller: ObjectsUserBundle:User:loginNameCheck, loginName: ~ }
