ObjectsKarasBundle_employee_experience:
    resource: "@ObjectsKarasBundle/Resources/config/routing/experience.yml"
    prefix:   /employee/experience

ObjectsKarasBundle_employee_project:
    resource: "@ObjectsKarasBundle/Resources/config/routing/project.yml"
    prefix:   /employee/project

ObjectsKarasBundle_employee_course:
    resource: "@ObjectsKarasBundle/Resources/config/routing/course.yml"
    prefix:   /employee/course

ObjectsKarasBundle_employee_skill:
    resource: "@ObjectsKarasBundle/Resources/config/routing/skill.yml"
    prefix:   /employee/skill

ObjectsKarasBundle_employee_education:
    resource: "@ObjectsKarasBundle/Resources/config/routing/education.yml"
    prefix:   /employee/education

ObjectsKarasBundle_employee_language:
    resource: "@ObjectsKarasBundle/Resources/config/routing/language.yml"
    prefix:   /employee/language
    
ObjectsKarasBundle_employee_contact:
    resource: "@ObjectsKarasBundle/Resources/config/routing/contact.yml"
    prefix:   /employee/contact

ObjectsKarasBundle_employee_additional:
    resource: "@ObjectsKarasBundle/Resources/config/routing/additional.yml"
    prefix:   /employee/additional

ObjectsKarasBundle_employer_prrofile:
    resource: "@ObjectsKarasBundle/Resources/config/routing/company.yml"
    prefix:   /employer/profile
    
objects_karas_bundle_add_to_bookmark:
    pattern:  /employer/bookmark/add
    defaults: { _controller: ObjectsKarasBundle:Bookmark:add }

objects_karas_bundle_show_bookmark:
    pattern:  /employer/bookmark/show
    defaults: { _controller: ObjectsKarasBundle:Bookmark:show }

objects_karas_bundle_bookmark_inquire:
    pattern:  /employer/bookmark/inquire
    defaults: { _controller: ObjectsKarasBundle:Bookmark:inquire }

objects_karas_homepage:
    pattern:  /
    defaults: { _controller: ObjectsKarasBundle:Karas:index }

objects_karas_services:
    pattern:  /services
    defaults: { _controller: ObjectsKarasBundle:Karas:services }

objects_karas_contact:
    pattern:  /contact
    defaults: { _controller: ObjectsKarasBundle:Karas:contact }

objects_karas_email:
    pattern:  /email
    defaults: { _controller: ObjectsKarasBundle:Karas:email }

objects_karas_about:
    pattern:  /about
    defaults: { _controller: ObjectsKarasBundle:Karas:about }



objects_karas_employee_profile:
    pattern:  /employee/profile
    defaults: { _controller: ObjectsKarasBundle:Employee:profile }
    
objects_karas_employer_show_employee_profile:
    pattern:  /employer/user/view/{employeeId}
    defaults: { _controller: ObjectsKarasBundle:Employee:view }

objects_karas_employee_search:
    pattern:  /employee/search
    defaults: { _controller: ObjectsKarasBundle:Employee:search }

objects_karas_employee_filter:
    pattern:  /employee/filter/{page}
    defaults: { _controller: ObjectsKarasBundle:Employee:filter, page: 1 }


objects_karas_job_new:
    pattern:  /job/new
    defaults: { _controller: ObjectsKarasBundle:Job:new}

objects_karas_job_edit:
    pattern:  /job/edit/{id}
    defaults: { _controller: ObjectsKarasBundle:Job:edit}

objects_karas_job_list:
    pattern:  /job/list/{type}/{profession}/{page}
    defaults: { _controller: ObjectsKarasBundle:Job:list, type: all, profession: null, page: 1}
    
objects_karas_job_show:
    pattern:  /job/show/{id}
    defaults: { _controller: ObjectsKarasBundle:Job:show }

objects_karas_job_apply:
    pattern:  /job/apply/{id}
    defaults: { _controller: ObjectsKarasBundle:Job:apply }

objects_karas_job_search:
    pattern:  /job/search
    defaults: { _controller: ObjectsKarasBundle:Job:search}

objects_karas_job_filter:
    pattern:  /job/filter/{page}
    defaults: { _controller: ObjectsKarasBundle:Job:filter, page: 1 }